[package]
name = "phppp"
version = "0.1.0"
edition = "2024"

[lib]
name = "phppp"
path = "src/lib.rs"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
notify = "6"
rayon = "1"
bumpalo = "3"
tree-sitter = "0.25"
tree-sitter-php = "0.23"
dashmap = "5"
